type = "directrequest"
schemaVersion = 1
name = "getSettings"
externalJobID = "113c01aa-cf59-49d8-bb54-d84b54029b0d"
maxTaskDuration = "0s"
contractAddress = "0x05c0928f481e9993f33Dc0Af0f1372d08A3A3873"
minIncomingConfirmations = 0
minContractPaymentLinkJuels = "0"
observationSource = """
    decode_log   [type=ethabidecodelog
                  abi="OracleRequest(bytes32 indexed specId, address requester, bytes32 requestId, uint256 payment, address callbackAddr, bytes4 callbackFunctionId, uint256 cancelExpiration, uint256 dataVersion, bytes data)"
                  data="$(jobRun.logData)"
                  topics="$(jobRun.logTopics)"]
    decode_cbor  [type=cborparse 
                              data="$(decode_log.data)"]
    fetch        [type="bridge" name="Settings" requestData="{\\"data\\":{\\"username\\": $(decode_cbor.username), \\"address\\": $(decode_cbor.address)}}"]
    issuccess    [type="jsonparse" path="data,result,issuccess" data="$(fetch)"]
    encode_data  [type="ethabiencode" abi="(bool _isSuccess)" data="{ \\"_isSuccess\\": $(issuccess) }"]
    encode_tx    [type="ethabiencode"
                  abi="fulfillOracleRequest(bytes32 _requestId, uint256 payment, address callbackAddress, bytes4 callbackFunctionId, uint256 expiration, bytes32 _data)"
                  data="{\\"_requestId\\": $(decode_log.requestId), \\"payment\\": $(decode_log.payment), \\"callbackAddress\\": $(decode_log.callbackAddr), \\"callbackFunctionId\\": $(decode_log.callbackFunctionId), \\"expiration\\": $(decode_log.cancelExpiration), \\"_data\\": $(encode_data)}"
                 ]
    submit_tx    [type="ethtx" to="0x05c0928f481e9993f33Dc0Af0f1372d08A3A3873" data="$(encode_tx)"]

    decode_log -> decode_cbor -> fetch -> issuccess ->encode_data-> encode_tx -> submit_tx
"""